version: "2"

services:

    piwigo:
        image: linuxserver/piwigo
        container_name: piwigo
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Berlin
        volumes:
            - /home/pi/hdd-extern25/docker/piwigo:/config
            - /home/pi/hdd-extern25/piwigo/galleries:/config/www/gallery/galleries
            - /home/pi/hdd-extern25/piwigo/upload:/config/www/gallery/upload
        ports:
            - 10080:80
        networks:
            - farmedia    
        restart: unless-stopped
        
    mariadb:
        image: linuxserver/mariadb
        container_name: mariadb
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Berlin
            # To change the root password: go in the container and use: mysqladmin -u root password <PASSWORD>
            # - MYSQL_ROOT_PASSWORD=ROOT_ACCESS_PASSWORD
            # - MYSQL_DATABASE=USER_DB_NAME #optional
            # - MYSQL_USER=MYSQL_USER #optional
            # - MYSQL_PASSWORD=DATABASE_PASSWORD #optional
            # - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
        volumes:
            - /home/pi/hdd-extern25/docker/mariadb:/config
        networks:
            - farmedia     
        restart: unless-stopped
        
    letsencrypt:
        image: linuxserver/letsencrypt
        container_name: letsencrypt
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Berlin
            - VALIDATION=duckdns
            - DUCKDNSTOKEN=xxx
            - URL=farmedia.duckdns.org
            - SUBDOMAINS=wildcard
        volumes:
            - /home/pi/hdd-extern25/docker/letsencrypt:/config
        ports:
            - 443:443
            - 80:80
        networks:
            - farmedia     
        restart: unless-stopped
    
    phpmyadmin:
        image: ebspace/armhf-phpmyadmin:latest
        container_name: phpmyadmin
        depends_on:
            - mariadb
        ports:
            - 10081:80
        environment:
            PMA_HOST: mariadb
            PMA_USER: root
            PMA_PASSWORD: "secret"
        networks:
            - farmedia
        restart: unless-stopped
      
    duckdns:
        image: linuxserver/duckdns
        container_name: duckdns
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Berlin
            - SUBDOMAINS=xxx
            - TOKEN=xxx
            - LOG_FILE=true #optional
        volumes:
            - /home/pi/hdd-extern25/docker/duckdns:/config
        networks:
            - farmedia
        restart: unless-stopped      

    duplicati:
        image: linuxserver/duplicati
        container_name: duplicati
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Berlin
            - CLI_ARGS= #optional
        volumes:
            - /home/pi/hdd-extern25/docker/duplicati:/config
            - /home/pi/hdd-intern:/backups
            - /home/pi/hdd-extern25:/source
        ports:
            - 8200:8200
        networks:
            - farmedia  
        restart: unless-stopped

    heimdall:
        image: linuxserver/heimdall
        container_name: heimdall
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Berlin
        volumes:
            - /home/pi/hdd-extern25/docker/heimdall:/config
        ports:
            - 8888:80
        networks:
            - farmedia  
        restart: unless-stopped

networks:
    farmedia:
