version: "2"

services:

    piwigo:
        image: linuxserver/piwigo
        container_name: piwigo
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Berlin
        volumes:
            - /home/pi/hdd-extern25/docker/piwigo/config:/config
            - /home/pi/hdd-extern25/fotos:/config/www/gallery/galleries
        ports:
            - 10000:443
        networks:
            - piwigo    
        restart: unless-stopped
        
    mariadb:
        image: linuxserver/mariadb
        container_name: mariadb
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Berlin
            # To change the root password: go in the container and use: mysqladmin -u root password <PASSWORD>
            # - MYSQL_ROOT_PASSWORD=ROOT_ACCESS_PASSWORD
            # - MYSQL_DATABASE=USER_DB_NAME #optional
            # - MYSQL_USER=MYSQL_USER #optional
            # - MYSQL_PASSWORD=DATABASE_PASSWORD #optional
            # - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
        volumes:
            - /home/pi/hdd-extern25/docker/mariadb/config:/config
        ports:
            - 10010:3306
        networks:
            - piwigo     
        restart: unless-stopped
        
networks:
    piwigo:
